# Generated by Django 6.0.7 on 2026-07-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverter',
            name='company',
            field=models.CharField(choices=[('Desi', 'Desi'), ('Galaxy', 'Galaxy'), ('Hybrid', 'Hybrid')], max_length=20),
        ),
    ]
