# Generated by Django 6.0.7 on 2026-07-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_inverter_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverter',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
