# Generated by Django 6.0.7 on 2026-07-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_inverter_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverter',
            name='company',
            field=models.CharField(choices=[('None', 'None'), ('Desi', 'Desi'), ('Galaxy', 'Galaxy'), ('Hybrid', 'Hybrid')], max_length=20),
        ),
    ]
